version: '3.7'

services:

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${CUBE_KEY}
      - MINIO_SECRET_KEY=${CUBE_SECRET}
    command: server /data
    ports:
      - 9000:9000
    expose:
      - 9000
