name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CUBE_ACCESS: cube-access
      CUBE_SECRET: cube-secret
      CUBE_BUCKET: cube-bucket
      CUBE_REGION: cube-region
      CUBE_ENDPOINT: http://127.0.0.1:9000

    steps:
      - uses: actions/checkout@v2
      - name: Use Docker
        run: docker-compose up -d
      - run: sleep 20
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run lint
      - run: npm run test
